server:
  port: 8101

spring:
  application:
    name: BZ-Auth
  redis:
    database: 0
    host: 192.168.31.128
    port: 6379
    password: 123456
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: BaizitechHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.31.128:3306/baizitech_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
eureka:
  instance:
    #向Eureka 服务端发送心跳的间隔时间，单位为秒，用于服务续约。这里配置为20秒，即每隔20秒向baizitech-register发送心跳，表明当前服务没有宕机
    lease-renewal-interval-in-seconds: 20
  client:
    #为true时表示将当前服务注册到Eureak服务端
    register-with-eureka: true
    #为true时表示从Eureka 服务端获取注册的服务信息
    fetch-registry: true
    #新实例信息的变化到Eureka服务端的间隔时间，单位为秒
    instance-info-replication-interval-seconds: 30
    #默认值为30秒，即每30秒去Eureka服务端上获取服务并缓存，这里指定为3秒的原因是方便开发时测试，实际可以指定为默认值即可
    registry-fetch-interval-seconds: 3
    #指定Eureka服务端地址
    serviceUrl:
      defaultZone: http://baizitech:123456@localhost:8001/register/eureka/
mybatis-plus:
  type-aliases-package: com/baizitech/common/entity/system
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false